In [27]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statistics as stats
data = pd.read_csv('Iris.csv')
df = pd.read_csv('Titanic Dataset.csv')

In [8]:
#Mean
sepal_length_mean = np.mean(data['SepalLengthCm'])
print("Sepal length in cm:", sepal_length_mean)

Sepal length in cm: 5.843333333333334

In [9]:
sepal_width_mean = np.mean(data['SepalWidthCm'])
print("Sepal width in cm:", sepal_width_mean)

Sepal width in cm: 3.0540000000000003

In [10]:
petal_length_mean = np.mean(data['PetalLengthCm'])
print("Petal length in cm:", petal_length_mean)

Petal length in cm: 3.758666666666666

In [11]:
petal_width_mean = np.mean(data['PetalWidthCm'])
print("Petal width in cm:", petal_width_mean)

Petal width in cm: 1.1986666666666668

In [12]:
#Median
sepal_length_median = np.median(data['SepalLengthCm'])
print("Sepal length median:", sepal_length_median)

Sepal length median: 5.8

In [13]:
sepal_width_median = np.median(data['SepalWidthCm'])
print("Sepal width median:", sepal_width_median)

Sepal width median: 3.0

In [14]:
petal_length_median = np.median(data['PetalLengthCm'])
print("Petal length median:", petal_length_median)

Petal length median: 4.35

In [15]:
petal_width_median = np.median(data['PetalWidthCm'])
print("Petal length median:", petal_width_median)

Petal length median: 1.3

In [19]:
sepal_length_mode = stats.mode(np.array(data['SepalLengthCm']))
print("Sepal length mode:", sepal_length_mode)

Sepal length mode: 5.0

In [22]:
sepal_width_mode = stats.mode(data['SepalWidthCm'])
print("Sepal width mode:", sepal_width_mode)

Sepal width mode: 3.0

In [23]:
petal_length_mode = stats.mode(data['PetalLengthCm'])
print("Petal length mode:", petal_length_mode)

Petal length mode: 1.5

In [24]:
petal_width_mode = stats.mode(data['PetalWidthCm'])
print("Petal width mode:", petal_width_mode)

Petal width mode: 0.2

In [30]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,195.0,98.000000,56.435804,1.00,49.50,98.000000,146.5000,195.0
Survived,195.0,0.343590,0.476129,0.00,0.00,0.000000,1.0000,1.0
Pclass,195.0,2.420513,0.797929,1.00,2.00,3.000000,3.0000,3.0
Age,195.0,27.761731,13.592439,0.83,20.00,27.761731,33.0000,71.0
SibSp,195.0,0.697436,1.310443,0.00,0.00,0.000000,1.0000,8.0
Parch,195.0,0.441026,0.879526,0.00,0.00,0.000000,1.0000,5.0
Fare,195.0,27.283887,36.078740,0.00,8.05,15.050000,30.3833,263.0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  195 non-null    int64
 1   Survived     195 non-null    int64
 2   Pclass       195 non-null    int64
 3   Name         195 non-null    object
 4   Age          195 non-null    float64
 5   SibSp        195 non-null    int64
 6   Parch        195 non-null    int64
 7   Ticket       195 non-null    object
 8   Fare         195 non-null    float64
 9   Cabin        39 non-null     object
 10  Embarked     195 non-null    object
 11  Gender       195 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.4+ KB

In [33]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          156
Embarked         0
Gender           0
dtype: int64

In [35]:
df = df.dropna()
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
Gender         0
dtype: int64

In [41]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Gender
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,female
6,7,0,1,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,S,male
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,S,female
11,12,1,1,"Bonnell, Miss. Elizabeth",58.0,0,0,113783,26.5500,C103,S,female

In [57]:
#Titanic means
age_mean = np.mean(df['Age'])
print("Average age:", age_mean.round(1))

Average age: 34.7

dtype('float64')

In [49]:
fare_mean = np.mean(df['Fare'])
print("Average fare:", fare_mean.round(1))

Average fare: 63.8

In [50]:
#Titanic median
age_median = np.median(df['Age'])
print("Median of age:", age_median)

Median of age: 32.5

In [51]:
fare_median = np.median(df['Fare'])
print("Median of fare:", fare_median)

Median of fare: 51.8625

In [60]:
#Titanic mode
age_mode = stats.mode(df['Age'])
print("Most common age:", age_mode)

Most common age: 27.76173076923077

In [61]:
pclass_mode = stats.mode(df['Pclass'])
print("Most common class:", pclass_mode)

Most common class: 1

In [63]:
#Categorical mode with index 0
gender_mode = df['Gender'].value_counts().index[0]
print("Most prevalent gender:", gender_mode)

Most prevalent gender: male

In [64]:
#Categorical mode without index
gender_mode = df['Gender'].value_counts()
print("Most prevalent gender:", gender_mode)

Most prevalent gender: Gender
male      23
female    16
Name: count, dtype: int64

In [70]:
#Categorical mode with index 1
gender_mode = df['Gender'].value_counts().index[1]
print("Most prevalent gender:", gender_mode)

Most prevalent gender: female