In [1]:
#Step 1 Link database
import sqlite3
database = "database.sqlite"
conn = sqlite3.connect(database)
cursor = conn.cursor()
print("Data opened successfully.")

Data opened successfully.

In [2]:
import pandas as pd
tables = pd.read_sql("""SELECT * FROM sqlite_master
                     WHERE type = 'table'""", conn)

In [3]:
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [10]:
tables = pd.read_sql("""SELECT * FROM Win_By""", conn)

In [11]:
tables

   Win_Id   Win_Type
0       1       runs
1       2    wickets
2       3  NO Result
3       4        Tie

In [14]:
tables = pd.read_sql("""SELECT * FROM Win_By
                     WHERE Win_Type IS NULL""", conn)

In [16]:
tables

Empty DataFrame
Columns: [Win_Id, Win_Type]
Index: []

In [19]:
tables = pd.read_sql("""SELECT * FROM Player
                     WHERE Bowling_Skill IS NULL""", conn)

In [20]:
tables

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name
0,17,PA Patel,1985-03-09 00:00:00,1,None,1
1,36,M Rawat,1985-10-25 00:00:00,2,None,1
2,43,L Ronchi,1981-04-23 00:00:00,2,None,5
3,47,PR Shah,1987-11-03 00:00:00,2,None,1
4,62,WP Saha,1984-10-24 00:00:00,2,None,1
5,69,Kamran Akmal,1982-01-13 00:00:00,2,None,6
6,79,SS Tiwary,1989-12-30 00:00:00,1,None,1
7,88,KD Karthik,1985-06-01 00:00:00,2,None,1
8,107,SP Fleming,1973-04-01 00:00:00,1,None,4
9,114,YV Takawale,1984-11-05 00:00:00,2,None,1
10,123,DT Patil,1984-12-06 00:00:00,2,None,1
11,125,S Anirudha,1987-04-14 00:00:00,2,None,1
12,132,SP Goswami,1989-05-18 00:00:00,1,None,1
13,134,U Kaul,1987-12-02 00:00:00,1,None,1
14,138,NK Patel,1981-03-26 00:00:00,1,None,1
15,146,H Das,1986-12-10 00:00:00,2,None,1
16,183,NV Ojha,1983-07-20 00:00:00,2,None,1
17,207,AP Tare,1987-11-07 00:00:00,2,None,1
18,214,MS Bisla,1984-12-27 00:00:00,2,None,1
19,251,C Madan,1982-10-15 00:00:00,2,None,1
20,252,AG Paunikar,1988-04-18 00:00:00,2,None,1
21,260,MA Agarwal,1991-02-16 00:00:00,2,None,1
22,277,DH Yagnik,1983-06-22 00:00:00,1,None,1
23,279,BJ Haddin,1977-10-23 00:00:00,2,None,5
24,288,M Klinger,1980-07-04 00:00:00,2,None,5
25,319,N Saini,1988-10-28 00:00:00,2,None,1
26,327,BB Samantray,1988-12-14 00:00:00,2,None,1
27,341,MDKJ Perera,1990-08-17 00:00:00,1,None,7
28,351,SV Samson,1994-11-11 00:00:00,2,None,1
29,353,BJ Rohrer,1981-03-26 00:00:00,1,None,5
30,354,KL Rahul,1992-04-18 00:00:00,2,None,1
31,355,Q de Kock,1992-12-17 00:00:00,1,None,2
32,360,CM Gautam,1986-03-08 00:00:00,2,None,1
33,379,BR Dunk,1987-03-11 00:00:00,1,None,5
34,407,JC Buttler,1990-09-08 00:00:00,2,None,10
35,410,Ishan Kishan,1998-07-18 00:00:00,1,None,1
36,419,NS Naik,1994-11-09 00:00:00,2,None,1
37,420,RR Pant,1997-10-04 00:00:00,1,None,1
38,421,SW Billings,1991-06-15 00:00:00,2,None,10
39,423,PSP Handscomb,1991-04-26 00:00:00,2,None,5
40,433,ER Dwivedi,1988-07-22 00:00:00,2,None,1
41,466,P Dharmani,1974-09-27 00:00:00,2,None,1
42,468,KH Devdhar,1989-12-14 00:00:00,2,None,1

In [22]:
tables = pd.read_sql("""SELECT * FROM Player
                     WHERE Bowling_Skill IS NOT NULL""", conn)

In [23]:
tables

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name
0,1,SC Ganguly,1972-07-08 00:00:00,1,1,1
1,2,BB McCullum,1981-09-27 00:00:00,2,1,4
2,3,RT Ponting,1974-12-19 00:00:00,2,1,5
3,4,DJ Hussey,1977-07-15 00:00:00,2,2,5
4,5,Mohammad Hafeez,1980-10-17 00:00:00,2,2,6
...,...,...,...,...,...,...
421,463,T Shamsi,1990-02-18 00:00:00,2,8,2
422,464,SM Boland,1989-04-11 00:00:00,2,3,5
423,465,DL Chahar,1992-08-07 00:00:00,2,1,1
424,467,RV Pawar,1979-09-06 00:00:00,1,7,1
425,469,T Mishra,1986-12-22 00:00:00,2,3,1

In [30]:
tables = pd.read_sql("""SELECT Bowling_Skill, COUNT(Player_Id) FROM Player
                     GROUP BY Bowling_Skill""", conn)

In [31]:
tables

    Bowling_skill  COUNT(Player_Id)
0             NaN                43
1             1.0               104
2             2.0                81
3             3.0                53
4             4.0                21
5             5.0                38
6             6.0                13
7             7.0                44
8             8.0                 5
9             9.0                 8
10           10.0                24
11           11.0                20
12           12.0                 1
13           13.0                11
14           14.0                 3